---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
data:
  maxmemory: 2mb

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-svc
  labels:
    app: valkey
spec:
  type: NodePort
  selector:
    app: valkey
  ports:
    - port: 6379
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey-container
          image: docker.io/library/valkey:7.2.5
          args: ["--args", "valkey", "--protected-mode", "no"]
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /valkey-master-data
            - name: valkey-config
              mountPath: /valkey-master
      volumes:
        - name: valkey-config
          configMap:
            name: valkey-config
        - name: data
          emptyDir: {}
